### ISSUE TITLE
Different files for Free and Pro version

### ISSUE THREAD

**Issue by tsjdev-apps** [matthewrdev/fa2cs#1]
Hi @matthewrdev,

I want to know if there is a secondary file which only contains the free availble Icons, because currently also Icons which are only available in the Pro Version are in the file `FontAwesomeIcons.cs`. The problem is that if you are using an icon which is only available in the Pro Version you will see Nothing withtin the app and don't get any error message.

So it would be great if there are two versions of the file one for the Free fonts and one for the Pro fonts.

Thanks.

**Comment by matthewrdev** [comment]
Hi @tsjdev-apps,

Could you give an example of what you think the API for this would look like?

I'm not opposed to it, however, each property that represents an icon code in [FontAwesomeIcons.cs](https://github.com/matthewrdev/fa2cs/blob/master/FontAwesomeIcons.cs) lists the supported styles and if a Pro license is required.

For example:

```
/// <summary>
/// fa-address-book unicode value.
/// <para/>
/// This icon supports the following styles: Light (Pro), Regular, Solid
/// <para/>
/// See https://fontawesome.com/icons/address-book
/// </summary>
public const string AddressBook = "\uf2b9";
```

There are many cases where icons are free however they are Pro in certain styles. For example, the [fa-arrow-circle icon](https://fontawesome.com/icons/arrow-circle-up?style=solid) is free in Solid but Pro in Regular and Light.

**Comment by tsjdev-apps** [comment]
Hi @matthewrdev,

thanks for your reply. I see that this is a thought point. And I'm also not sure how to deal with that.

So maybe the user should have the option to define the selected style, like Pro - Regular or Free - Solid. Regarding that selection the list gets filtered.

**Comment by matthewrdev** [comment]
Closing this issue as the existing API documentation fulfils the requirement and this request has not been raised by other consumers.
