### ISSUE TITLE
Question mark inside the square instead of the Icon.

### ISSUE THREAD

**Issue by mfaizey** [matthewrdev/fa2cs#10]
Hello, Matthew. thanks for creating this. I am using the bars icon in the XAML file but it is showing a question mark instead of the icon. Can you let me how to get the icon?
<img width="448" alt="Screenshot 2022-06-17 at 1 14 34 AM" src="https://user-images.githubusercontent.com/40601789/174156229-1124a1d5-c072-4e7a-a881-8ffdcd930f6d.png">

**Comment by JeanMarcMbouma** [comment]
Hi there! I think you're missing the font family. You need to apply the font family to get the font image to appear.
I hope this helps

**Comment by matthewrdev** [comment]
Hey @Muhammadfaizann!

As per @JeanMarcMbouma said, this happens when the font family is not correctly setup.

How have you declared the font family? Also, is the font within the relevant platform projects?

**Comment by mfaizey** [comment]
Thanks. it was the missing font family, that was not properly set up. it's been fixed now. :)

**Comment by matthewrdev** [comment]
Great to hear! Nicely done on solving it, I’ll close this issue now. Please reopen if you need anymore help 🙂
