### ISSUE TITLE
Update for FontAwesome v6.2.0 icons

### ISSUE THREAD

**Issue by pasha-o** [matthewrdev/fa2cs#11]
Hi @matthewrdev 
will be there an update for the v6.2.0 version?

**Comment by matthewrdev** [comment]
Hi @pasha-o!

Thanks for flagging this, I wasn't aware of the FontAwesome 6.2 release. I'll rerun the generator now and update the icon code file.

**Comment by matthewrdev** [comment]
@pasha-o, I've just re-run the generator on the v6.2.0 version of FontAwesome.

The newly created icons file can be found here: https://raw.githubusercontent.com/matthewrdev/fa2cs/master/FontAwesomeIcons.cs

Have a great day!

**Comment by pasha-o** [comment]
thank you
