### ISSUE TITLE
Using it in Xaml

### ISSUE THREAD

**Issue by Joebu** [matthewrdev/fa2cs#2]
I tried using it in XAML as your demo but it doesn't work (setting the text in code behind does work)

 `<Label Text="{x:Static fontAwesome:FontAwesomeIcons.AmazonPay}"/>`

**Comment by matthewrdev** [comment]
Hi @Joebu,

Are you applying the correct FontAwesome font file to the label?

For [fa-amazon-pay](https://fontawesome.com/icons/amazon-pay?style=brands), you will need to apply the FontAwesome 5 Brands font family. 

See: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#setting-the-font-in-xaml

**Comment by matthewrdev** [comment]
Also, can you elaborate on "doesn't work"?

Does the code compile? Does the app crash at runtime? Does the icon simply not render?

**Comment by Joebu** [comment]
Sorry I didn't set the right font
