### ISSUE TITLE
Equals icon causes code analysis warning

### ISSUE THREAD

**Issue by W0GER** [matthewrdev/fa2cs#3]
First, thanks for the great work on providing this simple class, it makes the XAML code much more readable. 

In our projects we are leveraging the Microsoft.CodeAnalysis.FxCopAnalyzers in our projects. When I brought the FontAwesomeIcons.cs class into our project, the analyzers raised a warning: 

> warning CS0108: 'FontAwesomeIcons.Equals' hides inherited member 'object.Equals(object)'. Use the new keyword if hiding was intended.

To fix, I simply changed the `Equals` string to `Equal` (removing the trailing `s`). Very minor issue, but would be nice to have this in the source instead of updating it on each iteration.

**Comment by matthewrdev** [comment]
@W0GER Yes this makes sense. For the moment I'll include a deprecation warning on `Equals` to direct people to `Equal` as it's likely that people are using the `Equals` icon. After 3 months, I'll remove the old API completely.

**Comment by matthewrdev** [comment]
@W0GER I've implement this change and now agree that your suggestion of changing `Equals` to `Equal` is the correct course of action. I've removed `Equals` and replaced it with `Equal`.
