### ISSUE TITLE
Any idea why this might not work ?

### ISSUE THREAD

**Issue by stephenhauck** [matthewrdev/fa2cs#7]
I made the same .cs file using https://andreinitescu.github.io/IconFont2Code/

So ... when I try to use it like so it does not work
![image](https://user-images.githubusercontent.com/12648793/110037976-242e6800-7d0d-11eb-9d75-cca24b676f48.png)

MFractor knows what it is in the hover but ... no dice in the UI

![image](https://user-images.githubusercontent.com/12648793/110038063-40caa000-7d0d-11eb-952c-51d1bc0a00a3.png)

Is my XAML off or ???
The fact that MFractor can show it tells me it's probably a Shell framework issue ?
Any direction you can offer would be appreciated ...

**Comment by matthewrdev** [comment]
Hi @stephenhauck, I don't think your XAML is off, I've encountered font rendering issues before in Xamarin.Forms.

Can you attach the font and the font icon file to this issue and I'll attempt to reproduce? What platform(s) are you seeing this issue on?

**Comment by stephenhauck** [comment]
I am seeing this on Android and iOS
I am simply using the Font Awesome otf fonts and generating the C# class here 
https://andreinitescu.github.io/IconFont2Code/


I reported it here a few days ago but it seems no one understands or cares ...
https://github.com/MicrosoftDocs/xamarin-docs/issues/3255

**Comment by stephenhauck** [comment]
I have them all registered like this ..
![image](https://user-images.githubusercontent.com/12648793/110162643-fef93280-7dbc-11eb-9ec1-5db97941e975.png)

And generated literals for each 
![image](https://user-images.githubusercontent.com/12648793/110162708-159f8980-7dbd-11eb-8c7b-899994e664be.png)

And they are all set to "Embedded Resource"

None of them work ...

**Comment by matthewrdev** [comment]
@stephenhauck Doing some house keeping on the issue in this repo. Did you end up getting this to work?

**Comment by matthewrdev** [comment]
@stephenhauck I'm closing this issue as it's 6+ months old and, hopefully, you managed to get this to work. Please reach out again if you need further help :)
