### ISSUE TITLE
Font Awesome 6 Support

### ISSUE THREAD

**Issue by adamhill** [matthewrdev/fa2cs#8]
Is there a tool that generates this? 

I have access to the FA 6.0 beta and would like to use the new icons.

I am willing to do the work and make a PR.

**Comment by matthewrdev** [comment]
Hi @adamhill, thanks for offering to update the generator + icon code class.

At the moment, fa2cs inspects the [public cheatsheet](https://fontawesome.com/v5/cheatsheet/pro) and parses the json data encoded within it. 

[Please see this part of the codebase.](https://github.com/matthewrdev/fa2cs/blob/master/fa2cs/Program.cs#L34)

To update the generator, the v6 icons and their code-points will need to be accessible through the cheat sheet. It doesn't look like there is a cheatsheet available yet for the v6 icons: https://fontawesome.com/v6/cheatsheet/pro

**Comment by AustinAHunter** [comment]
Hey @matthewrdev
It looks like FontAwesome makes the .json file for their icons available on their public GitHub repo in their metadata folder. Would it be possible to use this file instead of the publicly available cheatsheet? It looks like it should provide the correct info for this to work. Probably almost identical to the schema being used on their cheatsheet page.

**Comment by matthewrdev** [comment]
Hey @AustinAHunter!

Thanks for making me aware of this, it's great to see that a publicly available JSON file is now available.

I've had a cursory look and couldn't find it; would you mind linking me to its location and I'll rejig the code generator to use it? This will get FontAwesome 6 support added to the project 🙂

**Comment by AustinAHunter** [comment]
@matthewrdev You are the man!
The link to the metadata folder can be found here: https://github.com/FortAwesome/Font-Awesome/blob/6.x/metadata/ and the specific link to the JSON file is https://github.com/FortAwesome/Font-Awesome/blob/6.x/metadata/icons.json. You'll see they also have a YAML file for the icons as well in that same metadata folder in case you wanted to use that. Looks like they left some options open.

**Comment by matthewrdev** [comment]
Thanks for the link @AustinAHunter!  Holy moly that's a big JSON file 😅

It'll take me a little bit of time to restructure the project to consume the JSON  as I have a few other things on the go so I thank you for your patience!

**Comment by AustinAHunter** [comment]
No problem @matthewrdev! I'm glad you are willing to continue to update the project as things change. I, for one, know it has really helped me out in the past with FA5 and making code a lot more readable, especially in a Xamarin.Forms project with a XAML based UI. I look forward to using the great new looking icons in FA6!

**Comment by matthewrdev** [comment]
@AustinAHunter Had a further look into this and it appears that the `meta/icons.json` file only contains the metadata for the free icon set. Unfortunately it won't work just yet as all icons (incl Pro) need to be in the final class for it to be truely useful. 🙄

I've just opened a [ticket in their repo](https://github.com/FortAwesome/Font-Awesome/issues/18826) to get some clarification.

**Comment by matthewrdev** [comment]
@AustinAHunter @adamhill I've just completed upgrading `fa2cs` to support Font Awesome 6.1.1.

Please find the updated class file here: https://raw.githubusercontent.com/matthewrdev/fa2cs/master/FontAwesomeIcons.cs
