### ISSUE TITLE
Glyphs don't match font

### ISSUE THREAD

**Issue by developerMicaelRoche** [matthewrdev/fa2cs#9]
Using the FontAwesomeIcons.cs, I've had issues matching the glyphs to the fonts.

I recommend having separate classes for each font (solid, regular, brands).

That way, instead of:
`<FontImageSource FontFamily="FARegular" Glyph="{x:Static fa:FontAwesomeIcons.AddressBook}" />`

You can do:
`<FontImageSource FontFamily="FARegular" Glyph="{x:Static fa:FontAwesomeRegular.AddressBook}" />`

With the assistance of IntelliSense, having the font match the glyph class gives a clear indicator whether or not the icon exists in the selected font.

I've gone ahead and created these 3 classes for my own projects, please feel free to take them, and maybe pretty them up.
[FontAwesomeBrands.cs](https://github.com/SmellyFatDuck/fa2cs/blob/master/FontAwesomeBrands.cs)
[FontAwesomeRegular.cs](https://github.com/SmellyFatDuck/fa2cs/blob/master/FontAwesomeRegular.cs)
[FontAwesomeSolid.cs](https://github.com/SmellyFatDuck/fa2cs/blob/master/FontAwesomeSolid.cs)

**Comment by matthewrdev** [comment]
Hi @SmellyFatDuck, thanks for using the project and for the great feedback.

The existing FontAwesomeIcons class does include API documentation for each glyph that lists the font families it is in. To me this is enough, however, I understand it doesn't enforce strictness for which glyphs are in which families.

I'd keep the existing FontAwesomeIcons class that has all the icons and then also generate a family specific font class (as suggested) that contains only its icons.

Would that work for you?

**Comment by developerMicaelRoche** [comment]
Yeah definitely, it was more of a suggestion than anything, thanks for getting back to me.

**Comment by matthewrdev** [comment]
No problem :)

I'm about to start the work to support FontAwesome 6.0 so the request is good timing. Lemme see what I can whip up.
